/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurveysSurveyIdRouteImport } from './routes/surveys.$surveyId'
import { Route as OrganizerSurveysRouteImport } from './routes/organizer.surveys'
import { Route as OrganizerProposalsRouteImport } from './routes/organizer.proposals'
import { Route as OrganizerPaymentsRouteImport } from './routes/organizer.payments'
import { Route as OrganizerManuscriptsRouteImport } from './routes/organizer.manuscripts'
import { Route as OrganizerExportRouteImport } from './routes/organizer.export'
import { Route as OrganizerActivitiesRouteImport } from './routes/organizer.activities'
import { Route as MyProposalsRouteImport } from './routes/my.proposals'
import { Route as FilesSplatRouteImport } from './routes/files.$'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as ApiSurveysRouteImport } from './routes/api/surveys'
import { Route as ActivitiesActivityIdRouteImport } from './routes/activities_.$activityId'
import { Route as ProjectsProjectIdPaymentRouteImport } from './routes/projects_.$projectId.payment'
import { Route as ProjectsProjectIdManuscriptRouteImport } from './routes/projects_.$projectId.manuscript'
import { Route as ProjectsProjectIdAuthorsRouteImport } from './routes/projects_.$projectId.authors'
import { Route as OrganizerActivitiesActivityIdRouteImport } from './routes/organizer.activities_.$activityId'
import { Route as ApiProjectsProposalsRouteImport } from './routes/api/projects/proposals'
import { Route as ApiProjectsPaymentCodeRouteImport } from './routes/api/projects/payment-code'
import { Route as ApiProjectsManuscriptsRouteImport } from './routes/api/projects/manuscripts'
import { Route as ApiProjectsAuthorsRouteImport } from './routes/api/projects/authors'
import { Route as ApiPasswordResetRequestRouteImport } from './routes/api/password-reset/request'
import { Route as ApiOrganizerSurveysRouteImport } from './routes/api/organizer/surveys'
import { Route as ApiOrganizerSurveyExportRouteImport } from './routes/api/organizer/survey-export'
import { Route as ApiOrganizerProposalsRouteImport } from './routes/api/organizer/proposals'
import { Route as ApiOrganizerPaymentsRouteImport } from './routes/api/organizer/payments'
import { Route as ApiOrganizerManuscriptsRouteImport } from './routes/api/organizer/manuscripts'
import { Route as ApiOrganizerExportRouteImport } from './routes/api/organizer/export'
import { Route as ApiOrganizerActivityConfigRouteImport } from './routes/api/organizer/activity-config'
import { Route as ApiOrganizerActivitiesRouteImport } from './routes/api/organizer/activities'
import { Route as ApiMyProposalsRouteImport } from './routes/api/my/proposals'
import { Route as ApiCronDdlRemindersRouteImport } from './routes/api/cron/ddl-reminders'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminPresetsRouteImport } from './routes/api/admin/presets'
import { Route as ApiAdminOrganizersRouteImport } from './routes/api/admin/organizers'
import { Route as ApiAdminEmailTemplatesRouteImport } from './routes/api/admin/email-templates'
import { Route as ApiAdminActivitiesRouteImport } from './routes/api/admin/activities'
import { Route as ActivitiesActivityIdProposalRouteImport } from './routes/activities_.$activityId.proposal'
import { Route as ApiAuthRegisterVerifyRouteImport } from './routes/api/auth/register/verify'
import { Route as ApiAuthRegisterBeginRouteImport } from './routes/api/auth/register/begin'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysSurveyIdRoute = SurveysSurveyIdRouteImport.update({
  id: '/surveys/$surveyId',
  path: '/surveys/$surveyId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerSurveysRoute = OrganizerSurveysRouteImport.update({
  id: '/organizer/surveys',
  path: '/organizer/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerProposalsRoute = OrganizerProposalsRouteImport.update({
  id: '/organizer/proposals',
  path: '/organizer/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerPaymentsRoute = OrganizerPaymentsRouteImport.update({
  id: '/organizer/payments',
  path: '/organizer/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerManuscriptsRoute = OrganizerManuscriptsRouteImport.update({
  id: '/organizer/manuscripts',
  path: '/organizer/manuscripts',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerExportRoute = OrganizerExportRouteImport.update({
  id: '/organizer/export',
  path: '/organizer/export',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerActivitiesRoute = OrganizerActivitiesRouteImport.update({
  id: '/organizer/activities',
  path: '/organizer/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProposalsRoute = MyProposalsRouteImport.update({
  id: '/my/proposals',
  path: '/my/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesSplatRoute = FilesSplatRouteImport.update({
  id: '/files/$',
  path: '/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSurveysRoute = ApiSurveysRouteImport.update({
  id: '/api/surveys',
  path: '/api/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesActivityIdRoute = ActivitiesActivityIdRouteImport.update({
  id: '/activities_/$activityId',
  path: '/activities/$activityId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdPaymentRoute =
  ProjectsProjectIdPaymentRouteImport.update({
    id: '/projects_/$projectId/payment',
    path: '/projects/$projectId/payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdManuscriptRoute =
  ProjectsProjectIdManuscriptRouteImport.update({
    id: '/projects_/$projectId/manuscript',
    path: '/projects/$projectId/manuscript',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdAuthorsRoute =
  ProjectsProjectIdAuthorsRouteImport.update({
    id: '/projects_/$projectId/authors',
    path: '/projects/$projectId/authors',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizerActivitiesActivityIdRoute =
  OrganizerActivitiesActivityIdRouteImport.update({
    id: '/organizer/activities_/$activityId',
    path: '/organizer/activities/$activityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsProposalsRoute = ApiProjectsProposalsRouteImport.update({
  id: '/api/projects/proposals',
  path: '/api/projects/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsPaymentCodeRoute = ApiProjectsPaymentCodeRouteImport.update({
  id: '/api/projects/payment-code',
  path: '/api/projects/payment-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsManuscriptsRoute = ApiProjectsManuscriptsRouteImport.update({
  id: '/api/projects/manuscripts',
  path: '/api/projects/manuscripts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsAuthorsRoute = ApiProjectsAuthorsRouteImport.update({
  id: '/api/projects/authors',
  path: '/api/projects/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPasswordResetRequestRoute = ApiPasswordResetRequestRouteImport.update({
  id: '/api/password-reset/request',
  path: '/api/password-reset/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizerSurveysRoute = ApiOrganizerSurveysRouteImport.update({
  id: '/api/organizer/surveys',
  path: '/api/organizer/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizerSurveyExportRoute =
  ApiOrganizerSurveyExportRouteImport.update({
    id: '/api/organizer/survey-export',
    path: '/api/organizer/survey-export',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrganizerProposalsRoute = ApiOrganizerProposalsRouteImport.update({
  id: '/api/organizer/proposals',
  path: '/api/organizer/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizerPaymentsRoute = ApiOrganizerPaymentsRouteImport.update({
  id: '/api/organizer/payments',
  path: '/api/organizer/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizerManuscriptsRoute = ApiOrganizerManuscriptsRouteImport.update({
  id: '/api/organizer/manuscripts',
  path: '/api/organizer/manuscripts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizerExportRoute = ApiOrganizerExportRouteImport.update({
  id: '/api/organizer/export',
  path: '/api/organizer/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizerActivityConfigRoute =
  ApiOrganizerActivityConfigRouteImport.update({
    id: '/api/organizer/activity-config',
    path: '/api/organizer/activity-config',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrganizerActivitiesRoute = ApiOrganizerActivitiesRouteImport.update({
  id: '/api/organizer/activities',
  path: '/api/organizer/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMyProposalsRoute = ApiMyProposalsRouteImport.update({
  id: '/api/my/proposals',
  path: '/api/my/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDdlRemindersRoute = ApiCronDdlRemindersRouteImport.update({
  id: '/api/cron/ddl-reminders',
  path: '/api/cron/ddl-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPresetsRoute = ApiAdminPresetsRouteImport.update({
  id: '/api/admin/presets',
  path: '/api/admin/presets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrganizersRoute = ApiAdminOrganizersRouteImport.update({
  id: '/api/admin/organizers',
  path: '/api/admin/organizers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEmailTemplatesRoute = ApiAdminEmailTemplatesRouteImport.update({
  id: '/api/admin/email-templates',
  path: '/api/admin/email-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminActivitiesRoute = ApiAdminActivitiesRouteImport.update({
  id: '/api/admin/activities',
  path: '/api/admin/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesActivityIdProposalRoute =
  ActivitiesActivityIdProposalRouteImport.update({
    id: '/proposal',
    path: '/proposal',
    getParentRoute: () => ActivitiesActivityIdRoute,
  } as any)
const ApiAuthRegisterVerifyRoute = ApiAuthRegisterVerifyRouteImport.update({
  id: '/api/auth/register/verify',
  path: '/api/auth/register/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterBeginRoute = ApiAuthRegisterBeginRouteImport.update({
  id: '/api/auth/register/begin',
  path: '/api/auth/register/begin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRouteWithChildren
  '/api/surveys': typeof ApiSurveysRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/files/$': typeof FilesSplatRoute
  '/my/proposals': typeof MyProposalsRoute
  '/organizer/activities': typeof OrganizerActivitiesRoute
  '/organizer/export': typeof OrganizerExportRoute
  '/organizer/manuscripts': typeof OrganizerManuscriptsRoute
  '/organizer/payments': typeof OrganizerPaymentsRoute
  '/organizer/proposals': typeof OrganizerProposalsRoute
  '/organizer/surveys': typeof OrganizerSurveysRoute
  '/surveys/$surveyId': typeof SurveysSurveyIdRoute
  '/activities/$activityId/proposal': typeof ActivitiesActivityIdProposalRoute
  '/api/admin/activities': typeof ApiAdminActivitiesRoute
  '/api/admin/email-templates': typeof ApiAdminEmailTemplatesRoute
  '/api/admin/organizers': typeof ApiAdminOrganizersRoute
  '/api/admin/presets': typeof ApiAdminPresetsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/ddl-reminders': typeof ApiCronDdlRemindersRoute
  '/api/my/proposals': typeof ApiMyProposalsRoute
  '/api/organizer/activities': typeof ApiOrganizerActivitiesRoute
  '/api/organizer/activity-config': typeof ApiOrganizerActivityConfigRoute
  '/api/organizer/export': typeof ApiOrganizerExportRoute
  '/api/organizer/manuscripts': typeof ApiOrganizerManuscriptsRoute
  '/api/organizer/payments': typeof ApiOrganizerPaymentsRoute
  '/api/organizer/proposals': typeof ApiOrganizerProposalsRoute
  '/api/organizer/survey-export': typeof ApiOrganizerSurveyExportRoute
  '/api/organizer/surveys': typeof ApiOrganizerSurveysRoute
  '/api/password-reset/request': typeof ApiPasswordResetRequestRoute
  '/api/projects/authors': typeof ApiProjectsAuthorsRoute
  '/api/projects/manuscripts': typeof ApiProjectsManuscriptsRoute
  '/api/projects/payment-code': typeof ApiProjectsPaymentCodeRoute
  '/api/projects/proposals': typeof ApiProjectsProposalsRoute
  '/organizer/activities/$activityId': typeof OrganizerActivitiesActivityIdRoute
  '/projects/$projectId/authors': typeof ProjectsProjectIdAuthorsRoute
  '/projects/$projectId/manuscript': typeof ProjectsProjectIdManuscriptRoute
  '/projects/$projectId/payment': typeof ProjectsProjectIdPaymentRoute
  '/api/auth/register/begin': typeof ApiAuthRegisterBeginRoute
  '/api/auth/register/verify': typeof ApiAuthRegisterVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRouteWithChildren
  '/api/surveys': typeof ApiSurveysRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/files/$': typeof FilesSplatRoute
  '/my/proposals': typeof MyProposalsRoute
  '/organizer/activities': typeof OrganizerActivitiesRoute
  '/organizer/export': typeof OrganizerExportRoute
  '/organizer/manuscripts': typeof OrganizerManuscriptsRoute
  '/organizer/payments': typeof OrganizerPaymentsRoute
  '/organizer/proposals': typeof OrganizerProposalsRoute
  '/organizer/surveys': typeof OrganizerSurveysRoute
  '/surveys/$surveyId': typeof SurveysSurveyIdRoute
  '/activities/$activityId/proposal': typeof ActivitiesActivityIdProposalRoute
  '/api/admin/activities': typeof ApiAdminActivitiesRoute
  '/api/admin/email-templates': typeof ApiAdminEmailTemplatesRoute
  '/api/admin/organizers': typeof ApiAdminOrganizersRoute
  '/api/admin/presets': typeof ApiAdminPresetsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/ddl-reminders': typeof ApiCronDdlRemindersRoute
  '/api/my/proposals': typeof ApiMyProposalsRoute
  '/api/organizer/activities': typeof ApiOrganizerActivitiesRoute
  '/api/organizer/activity-config': typeof ApiOrganizerActivityConfigRoute
  '/api/organizer/export': typeof ApiOrganizerExportRoute
  '/api/organizer/manuscripts': typeof ApiOrganizerManuscriptsRoute
  '/api/organizer/payments': typeof ApiOrganizerPaymentsRoute
  '/api/organizer/proposals': typeof ApiOrganizerProposalsRoute
  '/api/organizer/survey-export': typeof ApiOrganizerSurveyExportRoute
  '/api/organizer/surveys': typeof ApiOrganizerSurveysRoute
  '/api/password-reset/request': typeof ApiPasswordResetRequestRoute
  '/api/projects/authors': typeof ApiProjectsAuthorsRoute
  '/api/projects/manuscripts': typeof ApiProjectsManuscriptsRoute
  '/api/projects/payment-code': typeof ApiProjectsPaymentCodeRoute
  '/api/projects/proposals': typeof ApiProjectsProposalsRoute
  '/organizer/activities/$activityId': typeof OrganizerActivitiesActivityIdRoute
  '/projects/$projectId/authors': typeof ProjectsProjectIdAuthorsRoute
  '/projects/$projectId/manuscript': typeof ProjectsProjectIdManuscriptRoute
  '/projects/$projectId/payment': typeof ProjectsProjectIdPaymentRoute
  '/api/auth/register/begin': typeof ApiAuthRegisterBeginRoute
  '/api/auth/register/verify': typeof ApiAuthRegisterVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activities_/$activityId': typeof ActivitiesActivityIdRouteWithChildren
  '/api/surveys': typeof ApiSurveysRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/files/$': typeof FilesSplatRoute
  '/my/proposals': typeof MyProposalsRoute
  '/organizer/activities': typeof OrganizerActivitiesRoute
  '/organizer/export': typeof OrganizerExportRoute
  '/organizer/manuscripts': typeof OrganizerManuscriptsRoute
  '/organizer/payments': typeof OrganizerPaymentsRoute
  '/organizer/proposals': typeof OrganizerProposalsRoute
  '/organizer/surveys': typeof OrganizerSurveysRoute
  '/surveys/$surveyId': typeof SurveysSurveyIdRoute
  '/activities_/$activityId/proposal': typeof ActivitiesActivityIdProposalRoute
  '/api/admin/activities': typeof ApiAdminActivitiesRoute
  '/api/admin/email-templates': typeof ApiAdminEmailTemplatesRoute
  '/api/admin/organizers': typeof ApiAdminOrganizersRoute
  '/api/admin/presets': typeof ApiAdminPresetsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/ddl-reminders': typeof ApiCronDdlRemindersRoute
  '/api/my/proposals': typeof ApiMyProposalsRoute
  '/api/organizer/activities': typeof ApiOrganizerActivitiesRoute
  '/api/organizer/activity-config': typeof ApiOrganizerActivityConfigRoute
  '/api/organizer/export': typeof ApiOrganizerExportRoute
  '/api/organizer/manuscripts': typeof ApiOrganizerManuscriptsRoute
  '/api/organizer/payments': typeof ApiOrganizerPaymentsRoute
  '/api/organizer/proposals': typeof ApiOrganizerProposalsRoute
  '/api/organizer/survey-export': typeof ApiOrganizerSurveyExportRoute
  '/api/organizer/surveys': typeof ApiOrganizerSurveysRoute
  '/api/password-reset/request': typeof ApiPasswordResetRequestRoute
  '/api/projects/authors': typeof ApiProjectsAuthorsRoute
  '/api/projects/manuscripts': typeof ApiProjectsManuscriptsRoute
  '/api/projects/payment-code': typeof ApiProjectsPaymentCodeRoute
  '/api/projects/proposals': typeof ApiProjectsProposalsRoute
  '/organizer/activities_/$activityId': typeof OrganizerActivitiesActivityIdRoute
  '/projects_/$projectId/authors': typeof ProjectsProjectIdAuthorsRoute
  '/projects_/$projectId/manuscript': typeof ProjectsProjectIdManuscriptRoute
  '/projects_/$projectId/payment': typeof ProjectsProjectIdPaymentRoute
  '/api/auth/register/begin': typeof ApiAuthRegisterBeginRoute
  '/api/auth/register/verify': typeof ApiAuthRegisterVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/activities'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/activities/$activityId'
    | '/api/surveys'
    | '/api/uploads'
    | '/files/$'
    | '/my/proposals'
    | '/organizer/activities'
    | '/organizer/export'
    | '/organizer/manuscripts'
    | '/organizer/payments'
    | '/organizer/proposals'
    | '/organizer/surveys'
    | '/surveys/$surveyId'
    | '/activities/$activityId/proposal'
    | '/api/admin/activities'
    | '/api/admin/email-templates'
    | '/api/admin/organizers'
    | '/api/admin/presets'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/cron/ddl-reminders'
    | '/api/my/proposals'
    | '/api/organizer/activities'
    | '/api/organizer/activity-config'
    | '/api/organizer/export'
    | '/api/organizer/manuscripts'
    | '/api/organizer/payments'
    | '/api/organizer/proposals'
    | '/api/organizer/survey-export'
    | '/api/organizer/surveys'
    | '/api/password-reset/request'
    | '/api/projects/authors'
    | '/api/projects/manuscripts'
    | '/api/projects/payment-code'
    | '/api/projects/proposals'
    | '/organizer/activities/$activityId'
    | '/projects/$projectId/authors'
    | '/projects/$projectId/manuscript'
    | '/projects/$projectId/payment'
    | '/api/auth/register/begin'
    | '/api/auth/register/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/activities'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/activities/$activityId'
    | '/api/surveys'
    | '/api/uploads'
    | '/files/$'
    | '/my/proposals'
    | '/organizer/activities'
    | '/organizer/export'
    | '/organizer/manuscripts'
    | '/organizer/payments'
    | '/organizer/proposals'
    | '/organizer/surveys'
    | '/surveys/$surveyId'
    | '/activities/$activityId/proposal'
    | '/api/admin/activities'
    | '/api/admin/email-templates'
    | '/api/admin/organizers'
    | '/api/admin/presets'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/cron/ddl-reminders'
    | '/api/my/proposals'
    | '/api/organizer/activities'
    | '/api/organizer/activity-config'
    | '/api/organizer/export'
    | '/api/organizer/manuscripts'
    | '/api/organizer/payments'
    | '/api/organizer/proposals'
    | '/api/organizer/survey-export'
    | '/api/organizer/surveys'
    | '/api/password-reset/request'
    | '/api/projects/authors'
    | '/api/projects/manuscripts'
    | '/api/projects/payment-code'
    | '/api/projects/proposals'
    | '/organizer/activities/$activityId'
    | '/projects/$projectId/authors'
    | '/projects/$projectId/manuscript'
    | '/projects/$projectId/payment'
    | '/api/auth/register/begin'
    | '/api/auth/register/verify'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/activities'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/activities_/$activityId'
    | '/api/surveys'
    | '/api/uploads'
    | '/files/$'
    | '/my/proposals'
    | '/organizer/activities'
    | '/organizer/export'
    | '/organizer/manuscripts'
    | '/organizer/payments'
    | '/organizer/proposals'
    | '/organizer/surveys'
    | '/surveys/$surveyId'
    | '/activities_/$activityId/proposal'
    | '/api/admin/activities'
    | '/api/admin/email-templates'
    | '/api/admin/organizers'
    | '/api/admin/presets'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/cron/ddl-reminders'
    | '/api/my/proposals'
    | '/api/organizer/activities'
    | '/api/organizer/activity-config'
    | '/api/organizer/export'
    | '/api/organizer/manuscripts'
    | '/api/organizer/payments'
    | '/api/organizer/proposals'
    | '/api/organizer/survey-export'
    | '/api/organizer/surveys'
    | '/api/password-reset/request'
    | '/api/projects/authors'
    | '/api/projects/manuscripts'
    | '/api/projects/payment-code'
    | '/api/projects/proposals'
    | '/organizer/activities_/$activityId'
    | '/projects_/$projectId/authors'
    | '/projects_/$projectId/manuscript'
    | '/projects_/$projectId/payment'
    | '/api/auth/register/begin'
    | '/api/auth/register/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ActivitiesActivityIdRoute: typeof ActivitiesActivityIdRouteWithChildren
  ApiSurveysRoute: typeof ApiSurveysRoute
  ApiUploadsRoute: typeof ApiUploadsRoute
  FilesSplatRoute: typeof FilesSplatRoute
  MyProposalsRoute: typeof MyProposalsRoute
  OrganizerActivitiesRoute: typeof OrganizerActivitiesRoute
  OrganizerExportRoute: typeof OrganizerExportRoute
  OrganizerManuscriptsRoute: typeof OrganizerManuscriptsRoute
  OrganizerPaymentsRoute: typeof OrganizerPaymentsRoute
  OrganizerProposalsRoute: typeof OrganizerProposalsRoute
  OrganizerSurveysRoute: typeof OrganizerSurveysRoute
  SurveysSurveyIdRoute: typeof SurveysSurveyIdRoute
  ApiAdminActivitiesRoute: typeof ApiAdminActivitiesRoute
  ApiAdminEmailTemplatesRoute: typeof ApiAdminEmailTemplatesRoute
  ApiAdminOrganizersRoute: typeof ApiAdminOrganizersRoute
  ApiAdminPresetsRoute: typeof ApiAdminPresetsRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronDdlRemindersRoute: typeof ApiCronDdlRemindersRoute
  ApiMyProposalsRoute: typeof ApiMyProposalsRoute
  ApiOrganizerActivitiesRoute: typeof ApiOrganizerActivitiesRoute
  ApiOrganizerActivityConfigRoute: typeof ApiOrganizerActivityConfigRoute
  ApiOrganizerExportRoute: typeof ApiOrganizerExportRoute
  ApiOrganizerManuscriptsRoute: typeof ApiOrganizerManuscriptsRoute
  ApiOrganizerPaymentsRoute: typeof ApiOrganizerPaymentsRoute
  ApiOrganizerProposalsRoute: typeof ApiOrganizerProposalsRoute
  ApiOrganizerSurveyExportRoute: typeof ApiOrganizerSurveyExportRoute
  ApiOrganizerSurveysRoute: typeof ApiOrganizerSurveysRoute
  ApiPasswordResetRequestRoute: typeof ApiPasswordResetRequestRoute
  ApiProjectsAuthorsRoute: typeof ApiProjectsAuthorsRoute
  ApiProjectsManuscriptsRoute: typeof ApiProjectsManuscriptsRoute
  ApiProjectsPaymentCodeRoute: typeof ApiProjectsPaymentCodeRoute
  ApiProjectsProposalsRoute: typeof ApiProjectsProposalsRoute
  OrganizerActivitiesActivityIdRoute: typeof OrganizerActivitiesActivityIdRoute
  ProjectsProjectIdAuthorsRoute: typeof ProjectsProjectIdAuthorsRoute
  ProjectsProjectIdManuscriptRoute: typeof ProjectsProjectIdManuscriptRoute
  ProjectsProjectIdPaymentRoute: typeof ProjectsProjectIdPaymentRoute
  ApiAuthRegisterBeginRoute: typeof ApiAuthRegisterBeginRoute
  ApiAuthRegisterVerifyRoute: typeof ApiAuthRegisterVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/$surveyId': {
      id: '/surveys/$surveyId'
      path: '/surveys/$surveyId'
      fullPath: '/surveys/$surveyId'
      preLoaderRoute: typeof SurveysSurveyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/surveys': {
      id: '/organizer/surveys'
      path: '/organizer/surveys'
      fullPath: '/organizer/surveys'
      preLoaderRoute: typeof OrganizerSurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/proposals': {
      id: '/organizer/proposals'
      path: '/organizer/proposals'
      fullPath: '/organizer/proposals'
      preLoaderRoute: typeof OrganizerProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/payments': {
      id: '/organizer/payments'
      path: '/organizer/payments'
      fullPath: '/organizer/payments'
      preLoaderRoute: typeof OrganizerPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/manuscripts': {
      id: '/organizer/manuscripts'
      path: '/organizer/manuscripts'
      fullPath: '/organizer/manuscripts'
      preLoaderRoute: typeof OrganizerManuscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/export': {
      id: '/organizer/export'
      path: '/organizer/export'
      fullPath: '/organizer/export'
      preLoaderRoute: typeof OrganizerExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/activities': {
      id: '/organizer/activities'
      path: '/organizer/activities'
      fullPath: '/organizer/activities'
      preLoaderRoute: typeof OrganizerActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/proposals': {
      id: '/my/proposals'
      path: '/my/proposals'
      fullPath: '/my/proposals'
      preLoaderRoute: typeof MyProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/$': {
      id: '/files/$'
      path: '/files/$'
      fullPath: '/files/$'
      preLoaderRoute: typeof FilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/surveys': {
      id: '/api/surveys'
      path: '/api/surveys'
      fullPath: '/api/surveys'
      preLoaderRoute: typeof ApiSurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities_/$activityId': {
      id: '/activities_/$activityId'
      path: '/activities/$activityId'
      fullPath: '/activities/$activityId'
      preLoaderRoute: typeof ActivitiesActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId/payment': {
      id: '/projects_/$projectId/payment'
      path: '/projects/$projectId/payment'
      fullPath: '/projects/$projectId/payment'
      preLoaderRoute: typeof ProjectsProjectIdPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId/manuscript': {
      id: '/projects_/$projectId/manuscript'
      path: '/projects/$projectId/manuscript'
      fullPath: '/projects/$projectId/manuscript'
      preLoaderRoute: typeof ProjectsProjectIdManuscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId/authors': {
      id: '/projects_/$projectId/authors'
      path: '/projects/$projectId/authors'
      fullPath: '/projects/$projectId/authors'
      preLoaderRoute: typeof ProjectsProjectIdAuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/activities_/$activityId': {
      id: '/organizer/activities_/$activityId'
      path: '/organizer/activities/$activityId'
      fullPath: '/organizer/activities/$activityId'
      preLoaderRoute: typeof OrganizerActivitiesActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/proposals': {
      id: '/api/projects/proposals'
      path: '/api/projects/proposals'
      fullPath: '/api/projects/proposals'
      preLoaderRoute: typeof ApiProjectsProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/payment-code': {
      id: '/api/projects/payment-code'
      path: '/api/projects/payment-code'
      fullPath: '/api/projects/payment-code'
      preLoaderRoute: typeof ApiProjectsPaymentCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/manuscripts': {
      id: '/api/projects/manuscripts'
      path: '/api/projects/manuscripts'
      fullPath: '/api/projects/manuscripts'
      preLoaderRoute: typeof ApiProjectsManuscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/authors': {
      id: '/api/projects/authors'
      path: '/api/projects/authors'
      fullPath: '/api/projects/authors'
      preLoaderRoute: typeof ApiProjectsAuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/password-reset/request': {
      id: '/api/password-reset/request'
      path: '/api/password-reset/request'
      fullPath: '/api/password-reset/request'
      preLoaderRoute: typeof ApiPasswordResetRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizer/surveys': {
      id: '/api/organizer/surveys'
      path: '/api/organizer/surveys'
      fullPath: '/api/organizer/surveys'
      preLoaderRoute: typeof ApiOrganizerSurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizer/survey-export': {
      id: '/api/organizer/survey-export'
      path: '/api/organizer/survey-export'
      fullPath: '/api/organizer/survey-export'
      preLoaderRoute: typeof ApiOrganizerSurveyExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizer/proposals': {
      id: '/api/organizer/proposals'
      path: '/api/organizer/proposals'
      fullPath: '/api/organizer/proposals'
      preLoaderRoute: typeof ApiOrganizerProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizer/payments': {
      id: '/api/organizer/payments'
      path: '/api/organizer/payments'
      fullPath: '/api/organizer/payments'
      preLoaderRoute: typeof ApiOrganizerPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizer/manuscripts': {
      id: '/api/organizer/manuscripts'
      path: '/api/organizer/manuscripts'
      fullPath: '/api/organizer/manuscripts'
      preLoaderRoute: typeof ApiOrganizerManuscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizer/export': {
      id: '/api/organizer/export'
      path: '/api/organizer/export'
      fullPath: '/api/organizer/export'
      preLoaderRoute: typeof ApiOrganizerExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizer/activity-config': {
      id: '/api/organizer/activity-config'
      path: '/api/organizer/activity-config'
      fullPath: '/api/organizer/activity-config'
      preLoaderRoute: typeof ApiOrganizerActivityConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizer/activities': {
      id: '/api/organizer/activities'
      path: '/api/organizer/activities'
      fullPath: '/api/organizer/activities'
      preLoaderRoute: typeof ApiOrganizerActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/my/proposals': {
      id: '/api/my/proposals'
      path: '/api/my/proposals'
      fullPath: '/api/my/proposals'
      preLoaderRoute: typeof ApiMyProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/ddl-reminders': {
      id: '/api/cron/ddl-reminders'
      path: '/api/cron/ddl-reminders'
      fullPath: '/api/cron/ddl-reminders'
      preLoaderRoute: typeof ApiCronDdlRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/presets': {
      id: '/api/admin/presets'
      path: '/api/admin/presets'
      fullPath: '/api/admin/presets'
      preLoaderRoute: typeof ApiAdminPresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/organizers': {
      id: '/api/admin/organizers'
      path: '/api/admin/organizers'
      fullPath: '/api/admin/organizers'
      preLoaderRoute: typeof ApiAdminOrganizersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/email-templates': {
      id: '/api/admin/email-templates'
      path: '/api/admin/email-templates'
      fullPath: '/api/admin/email-templates'
      preLoaderRoute: typeof ApiAdminEmailTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/activities': {
      id: '/api/admin/activities'
      path: '/api/admin/activities'
      fullPath: '/api/admin/activities'
      preLoaderRoute: typeof ApiAdminActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities_/$activityId/proposal': {
      id: '/activities_/$activityId/proposal'
      path: '/proposal'
      fullPath: '/activities/$activityId/proposal'
      preLoaderRoute: typeof ActivitiesActivityIdProposalRouteImport
      parentRoute: typeof ActivitiesActivityIdRoute
    }
    '/api/auth/register/verify': {
      id: '/api/auth/register/verify'
      path: '/api/auth/register/verify'
      fullPath: '/api/auth/register/verify'
      preLoaderRoute: typeof ApiAuthRegisterVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register/begin': {
      id: '/api/auth/register/begin'
      path: '/api/auth/register/begin'
      fullPath: '/api/auth/register/begin'
      preLoaderRoute: typeof ApiAuthRegisterBeginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ActivitiesActivityIdRouteChildren {
  ActivitiesActivityIdProposalRoute: typeof ActivitiesActivityIdProposalRoute
}

const ActivitiesActivityIdRouteChildren: ActivitiesActivityIdRouteChildren = {
  ActivitiesActivityIdProposalRoute: ActivitiesActivityIdProposalRoute,
}

const ActivitiesActivityIdRouteWithChildren =
  ActivitiesActivityIdRoute._addFileChildren(ActivitiesActivityIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ActivitiesActivityIdRoute: ActivitiesActivityIdRouteWithChildren,
  ApiSurveysRoute: ApiSurveysRoute,
  ApiUploadsRoute: ApiUploadsRoute,
  FilesSplatRoute: FilesSplatRoute,
  MyProposalsRoute: MyProposalsRoute,
  OrganizerActivitiesRoute: OrganizerActivitiesRoute,
  OrganizerExportRoute: OrganizerExportRoute,
  OrganizerManuscriptsRoute: OrganizerManuscriptsRoute,
  OrganizerPaymentsRoute: OrganizerPaymentsRoute,
  OrganizerProposalsRoute: OrganizerProposalsRoute,
  OrganizerSurveysRoute: OrganizerSurveysRoute,
  SurveysSurveyIdRoute: SurveysSurveyIdRoute,
  ApiAdminActivitiesRoute: ApiAdminActivitiesRoute,
  ApiAdminEmailTemplatesRoute: ApiAdminEmailTemplatesRoute,
  ApiAdminOrganizersRoute: ApiAdminOrganizersRoute,
  ApiAdminPresetsRoute: ApiAdminPresetsRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronDdlRemindersRoute: ApiCronDdlRemindersRoute,
  ApiMyProposalsRoute: ApiMyProposalsRoute,
  ApiOrganizerActivitiesRoute: ApiOrganizerActivitiesRoute,
  ApiOrganizerActivityConfigRoute: ApiOrganizerActivityConfigRoute,
  ApiOrganizerExportRoute: ApiOrganizerExportRoute,
  ApiOrganizerManuscriptsRoute: ApiOrganizerManuscriptsRoute,
  ApiOrganizerPaymentsRoute: ApiOrganizerPaymentsRoute,
  ApiOrganizerProposalsRoute: ApiOrganizerProposalsRoute,
  ApiOrganizerSurveyExportRoute: ApiOrganizerSurveyExportRoute,
  ApiOrganizerSurveysRoute: ApiOrganizerSurveysRoute,
  ApiPasswordResetRequestRoute: ApiPasswordResetRequestRoute,
  ApiProjectsAuthorsRoute: ApiProjectsAuthorsRoute,
  ApiProjectsManuscriptsRoute: ApiProjectsManuscriptsRoute,
  ApiProjectsPaymentCodeRoute: ApiProjectsPaymentCodeRoute,
  ApiProjectsProposalsRoute: ApiProjectsProposalsRoute,
  OrganizerActivitiesActivityIdRoute: OrganizerActivitiesActivityIdRoute,
  ProjectsProjectIdAuthorsRoute: ProjectsProjectIdAuthorsRoute,
  ProjectsProjectIdManuscriptRoute: ProjectsProjectIdManuscriptRoute,
  ProjectsProjectIdPaymentRoute: ProjectsProjectIdPaymentRoute,
  ApiAuthRegisterBeginRoute: ApiAuthRegisterBeginRoute,
  ApiAuthRegisterVerifyRoute: ApiAuthRegisterVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
