/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyProposalsRouteImport } from './routes/my.proposals'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as ActivitiesActivityIdRouteImport } from './routes/activities_.$activityId'
import { Route as ApiProjectsProposalsRouteImport } from './routes/api/projects/proposals'
import { Route as ApiPasswordResetRequestRouteImport } from './routes/api/password-reset/request'
import { Route as ApiMyProposalsRouteImport } from './routes/api/my/proposals'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ActivitiesActivityIdProposalRouteImport } from './routes/activities_.$activityId.proposal'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProposalsRoute = MyProposalsRouteImport.update({
  id: '/my/proposals',
  path: '/my/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesActivityIdRoute = ActivitiesActivityIdRouteImport.update({
  id: '/activities_/$activityId',
  path: '/activities/$activityId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsProposalsRoute = ApiProjectsProposalsRouteImport.update({
  id: '/api/projects/proposals',
  path: '/api/projects/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPasswordResetRequestRoute = ApiPasswordResetRequestRouteImport.update({
  id: '/api/password-reset/request',
  path: '/api/password-reset/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMyProposalsRoute = ApiMyProposalsRouteImport.update({
  id: '/api/my/proposals',
  path: '/api/my/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesActivityIdProposalRoute =
  ActivitiesActivityIdProposalRouteImport.update({
    id: '/proposal',
    path: '/proposal',
    getParentRoute: () => ActivitiesActivityIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/activities': typeof ActivitiesRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRouteWithChildren
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/my/proposals': typeof MyProposalsRoute
  '/activities/$activityId/proposal': typeof ActivitiesActivityIdProposalRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/my/proposals': typeof ApiMyProposalsRoute
  '/api/password-reset/request': typeof ApiPasswordResetRequestRoute
  '/api/projects/proposals': typeof ApiProjectsProposalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/activities': typeof ActivitiesRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRouteWithChildren
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/my/proposals': typeof MyProposalsRoute
  '/activities/$activityId/proposal': typeof ActivitiesActivityIdProposalRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/my/proposals': typeof ApiMyProposalsRoute
  '/api/password-reset/request': typeof ApiPasswordResetRequestRoute
  '/api/projects/proposals': typeof ApiProjectsProposalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/activities': typeof ActivitiesRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activities_/$activityId': typeof ActivitiesActivityIdRouteWithChildren
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/my/proposals': typeof MyProposalsRoute
  '/activities_/$activityId/proposal': typeof ActivitiesActivityIdProposalRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/my/proposals': typeof ApiMyProposalsRoute
  '/api/password-reset/request': typeof ApiPasswordResetRequestRoute
  '/api/projects/proposals': typeof ApiProjectsProposalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/activities'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/activities/$activityId'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/tanstack-query'
    | '/my/proposals'
    | '/activities/$activityId/proposal'
    | '/api/auth/$'
    | '/api/my/proposals'
    | '/api/password-reset/request'
    | '/api/projects/proposals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/activities'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/activities/$activityId'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/tanstack-query'
    | '/my/proposals'
    | '/activities/$activityId/proposal'
    | '/api/auth/$'
    | '/api/my/proposals'
    | '/api/password-reset/request'
    | '/api/projects/proposals'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/activities'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/activities_/$activityId'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/tanstack-query'
    | '/my/proposals'
    | '/activities_/$activityId/proposal'
    | '/api/auth/$'
    | '/api/my/proposals'
    | '/api/password-reset/request'
    | '/api/projects/proposals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ActivitiesActivityIdRoute: typeof ActivitiesActivityIdRouteWithChildren
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  MyProposalsRoute: typeof MyProposalsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMyProposalsRoute: typeof ApiMyProposalsRoute
  ApiPasswordResetRequestRoute: typeof ApiPasswordResetRequestRoute
  ApiProjectsProposalsRoute: typeof ApiProjectsProposalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/proposals': {
      id: '/my/proposals'
      path: '/my/proposals'
      fullPath: '/my/proposals'
      preLoaderRoute: typeof MyProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities_/$activityId': {
      id: '/activities_/$activityId'
      path: '/activities/$activityId'
      fullPath: '/activities/$activityId'
      preLoaderRoute: typeof ActivitiesActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/proposals': {
      id: '/api/projects/proposals'
      path: '/api/projects/proposals'
      fullPath: '/api/projects/proposals'
      preLoaderRoute: typeof ApiProjectsProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/password-reset/request': {
      id: '/api/password-reset/request'
      path: '/api/password-reset/request'
      fullPath: '/api/password-reset/request'
      preLoaderRoute: typeof ApiPasswordResetRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/my/proposals': {
      id: '/api/my/proposals'
      path: '/api/my/proposals'
      fullPath: '/api/my/proposals'
      preLoaderRoute: typeof ApiMyProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities_/$activityId/proposal': {
      id: '/activities_/$activityId/proposal'
      path: '/proposal'
      fullPath: '/activities/$activityId/proposal'
      preLoaderRoute: typeof ActivitiesActivityIdProposalRouteImport
      parentRoute: typeof ActivitiesActivityIdRoute
    }
  }
}

interface ActivitiesActivityIdRouteChildren {
  ActivitiesActivityIdProposalRoute: typeof ActivitiesActivityIdProposalRoute
}

const ActivitiesActivityIdRouteChildren: ActivitiesActivityIdRouteChildren = {
  ActivitiesActivityIdProposalRoute: ActivitiesActivityIdProposalRoute,
}

const ActivitiesActivityIdRouteWithChildren =
  ActivitiesActivityIdRoute._addFileChildren(ActivitiesActivityIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  ActivitiesRoute: ActivitiesRoute,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ActivitiesActivityIdRoute: ActivitiesActivityIdRouteWithChildren,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  MyProposalsRoute: MyProposalsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMyProposalsRoute: ApiMyProposalsRoute,
  ApiPasswordResetRequestRoute: ApiPasswordResetRequestRoute,
  ApiProjectsProposalsRoute: ApiProjectsProposalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
